### PR TITLE
eclib version 0.1

### PR DESCRIPTION
**Pull request by UnGitLambda**
Results of Eyal Cohen's 3month internship supervised by Wijnand Suijlen.

This contains a first version of a multi-send-recv function using libfabric and UDP.
It also contains some point to point communication function and of course an initialization for the structures used and a destruction function.

### CODE REVIEW

**Comment by anyzelman** [comment]
Crossref issue #3 and set merge target to dedicated branch

**Comment by anyzelman** [comment]
@UnHommeLambda @wijnand-suijlen -- thanks very much for the PR as well as the presentation earlier today!!

I'm missing the copyright headers. Would you like to add those prior to accepting into branch 3-* under issue #3 , or shall I do that? (This repo is Apache 2.0, example file headers are in any source file in master.)

Also we should add you to the NOTICE -- again, I can do that, or one of you is very welcome to make it part of this PR:) Lemme know how you like to proceed

**Comment by anyzelman** [comment]
Thanks!! I see a couple of files that are 3rd party. Just to confirm, those are modified from their original form right?

@wijnand-suijlen -- just to sync on a strategy for such sources, if indeed modified, we can put them in ./3rd/ectest maybe, with the Makefile?

**Comment by wijnand-suijlen** [comment]
We used these files from the libfabric source as template / example. I think that by the time we have a well performing all-to-all, these files will have been replaced completely by original code. That's also why this pull-request is not for the master but for a development branch.

**Comment by wijnand-suijlen** [comment]
So I don't have a preference for where these files  are stored, as long as they are!

**Comment by anyzelman** [comment]
(Tad bit late -- but yes, will follow the suggestion and merge into 3-towards-udp-and-libfabric-based-lpf-engines

**Pull request merged**
